language: go

go:
  - 1.9

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8
  - nvm use 8
  - npm install -g yarn
  - yarn install -prod false
  - touch .env

script:
  - make lint-frontend
  - make test-frontend
  - make dependencies-backend
  # uncommend next line when BE code will start passing go lint and go vet
  # - make lint-backend
  - make test
